project_name: htmltest

git:
  short_hash: true

builds:
  - binary: htmltest
    main: ./main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

changelog:
  sort: asc
  filters:
    exclude:
    - Merge pull request
    - Merge branch

archive:
  replacements:
    darwin: osx
    linux: linux
    windows: windows
    386: i386
    amd64: amd64
  format_overrides:
    - goos: windows
      format: zip

release:
  github:
    owner: wjdp
    name: htmltest

  draft: true


