language: go

go:
- 1.7.4

os:
- linux
- osx

install:
- go get -t ./... # Fetch all dependencies

script:
- ./coverage.sh   # Run test suite with coverage reporting
- go build -ldflags "-X main.buildDate=`date -u +%Y-%m-%dT%H:%M:%SZ`" -o bin/htmltest-$TRAVIS_OS_NAME -x main.go
- bin/htmltest-$TRAVIS_OS_NAME -h         # Print usage
- bin/htmltest-$TRAVIS_OS_NAME --version  # Print version
- bin/htmltest-$TRAVIS_OS_NAME --conf htmldoc/fixtures/conf.yaml # Run

after_success:
- bash <(curl -s https://codecov.io/bash) # Report coverage to codecov

before_deploy:
- chmod +x bin/htmltest-$TRAVIS_OS_NAME

deploy:
  provider: releases
  api_key:
    secure: ZV+Mttq0eaYALR9M/AQBnu9i0ytpT8bcWVvEwNjztRbLzsgGQOzReJiRI8gNUcrufRLI7G4n0feg9mCOLCD3kzG/7vYFiww2NzGk5zxLh8XSGDnTvd2Elm9DlCBmJTTgsS+HHxTo/0D4W5YeYo2UqWe8/5yvZHMdmKzqTRNwobccpkl9lCmUJXfX2tJ1fRlG6WKhTl7qhVVV/uj4m0pTOuVL3UmYiI5N5zFb/szAhGpmO0OHtlmRYqoaAcuBdml/dvfa4bcezuN63JIgb54DAMARjIGavJ8ehUeJKnsTXwNcEE/6AhTA9oMlEwNvy4FxZ28WpbzGupPOto6oW0apFdkeVaJ2eqzSd5kA6ql//Sc1EOQGyJmdDuHJ65/2JF5QnPaOzfid5PzUslrlC3Agby6Sikp0sLcfVamLe9P8PClvbm3qPI6UJf+B+miY0wYNhLnZUdBAuNTPwrorWt4RCTVyDAgdnFir6WSUsS7e5T+wgLh7YQ/YFRqORI719hGbNGfKurZEjCNchEbjVd0PhO3CUtWsh6P9Tn5HnJMcofWyqoxvOkSpeDVPYpwC+A095wqugp2T94kPAJUy05eR2q6va0jDtrwwmPcvGVnoH3kG8Hihxn0dANEIwighle/xOwle+xWr/x+8+tGedwhGeLal/sSCsUDYQi+Rpdk7AeY=
  file: bin/htmltest-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    tags: true
    repo: wjdp/htmltest
    go: 1.7.4
